# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-24 04:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_name', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Relationships',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company1', to='djangostocks.Company')),
                ('company2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company2', to='djangostocks.Company')),
                ('relationship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangostocks.Relationship')),
            ],
        ),
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('open', models.FloatField(null=True)),
                ('high', models.FloatField(null=True)),
                ('low', models.FloatField(null=True)),
                ('close', models.FloatField(null=True)),
                ('trade_value', models.FloatField(null=True)),
                ('trade_volume', models.FloatField(null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangostocks.Company')),
            ],
        ),
    ]
